# update all packages, unless marked with "pyup: ignore" in the requirements file
update: all

# enabling version pinning
pin: True

branch: master

# automatically discover requirements files
search: True

# Because updates generally trigger service reloads/restarts, it's better to batch
# these together when possible.
schedule: every week on wednesday

# Blacklist modules/slaveapi/files/requirements.txt
# Upgrades to this module breaks the SlaveAPI dashboard. BUG 1467573
requirements:
  - modules/slaveapi/files/requirements.txt:
      update: False
